# --- CONFIGURAZIONI GLOBALI CONDIVISE ---

[common]
platform = ststm32
framework = arduino
monitor_speed = 115200

# 1. GESTIONE LIBRERIE
lib_extra_dirs = 
    ../../shared_lib

# Librerie fisse che vuoi in OGNI progetto
lib_deps = 
    arduino-libraries/ArduinoBLE @ ^2.0.0

build_flags = -O3
    #commentare o passare in -O2 se ci sono problemi di compilazione o debug

# 2. DEFINIZIONI BASE PER I DUE CORE
[m7_base]
extends = common
board = portenta_h7_m7

[m4_base]
extends = common
board = portenta_h7_m4