[platformio]
extra_configs = ../../common_config.ini

[env:esp32-s3-n16r8_MAX_MTU]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = h2zero/NimBLE-Arduino @ ^2.1.0
build_src_filter = +<central/**>

[env:h7_MAX_MTU]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
    WiFi.h
    WiFiUdp.h
    chrono
build_flags =
    -I../../shared_lib
    -DSENSOR_ID=01  # <--- Definisce l'ID 1
lib_ldf_mode = deep+
build_src_filter = +<sensor/**>