[platformio]
extra_configs = ../../common_config.ini

# --- 1. SCHEDA CENTRALE (Sempre M7) ---
[env:h7_m7_central_v2]
extends = m7_base
lib_deps = 
    ${common.lib_deps}               ; Eredita le lib comuni
build_src_filter = +<central/**>

# --- 2. SCHEDA SENSORE (Core M7) ---
[env:h7_m7_sensor_v2]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
lib_ldf_mode = deep+
build_src_filter = +<sensor/m7/**>

# --- 3. SCHEDA SENSORE (Core M4) ---
[env:h7_m4_sensor_v2]
extends = m4_base
lib_deps = 
    ${common.lib_deps}
lib_ldf_mode = deep+
build_src_filter = +<sensor/m4/**>