[platformio]
extra_configs = ../../common_config.ini

# --- 1. SCHEDA CENTRALE (Sempre M7) ---
[env:portenta_h7_m7_central]
extends = m7_base
lib_deps = 
    ${common.lib_deps}               ; Eredita le lib comuni
build_src_filter = +<central/**>

# --- 2. SCHEDA SENSORE (Core M7) ---
[env:portenta_h7_m7_sensor]
extends = m7_base
lib_ldf_mode = deep+
lib_deps = 
    ${common.lib_deps}
build_src_filter = +<sensor/m7/**>

# --- 3. SCHEDA SENSORE (Core M4) ---
[env:portenta_h7_m4_sensor]
extends = m4_base
lib_ldf_mode = deep+
lib_deps = 
    ${common.lib_deps}
build_src_filter = +<sensor/m4/**>