[platformio]
# Usciamo da Blink e da Progetti per trovare il config nella root
extra_configs = ../../common_config.ini

[env:blink]
extends = m7_base
# Non servono librerie extra per il blink
build_src_filter = +<src/blink.cpp>