[platformio]
extra_configs = ../../common_config.ini

# Core m7 (ad alta potenza)
[env:h7_m7_test_dual_core]
extends = m7_base
lib_ldf_mode = deep+
lib_deps = 
    ${common.lib_deps}
build_src_filter = +<m7/**>

# Core m4 (a bassa potenza)
[env:h7_m4_test_dual_core]
extends = m4_base
lib_ldf_mode = deep+
lib_deps = 
    ${common.lib_deps}
build_src_filter = +<m4/**>