[platformio]
extra_configs = ../../common_config.ini

# --- 1. SCHEDA CENTRALE (Core M7) ---
[env:h7_m7_central_v1]
extends = m7_base
# La versione 2.0.0 è già definita nel common, la ereditiamo
build_src_filter = +<src/central/**>


# --- 2. SCHEDA SENSORE (Core M7) ---
[env:h7_m7_sensor_v1]
extends = m7_base

lib_deps = 
    ${common.lib_deps}
build_src_filter = +<src/sensor/**>
