[platformio]
extra_configs = ../../common_config.ini

# --- 1. SCHEDA CENTRALE ---
[env:h7_m7_central_real]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
    WiFi.h
    WiFiUdp.h
build_src_filter = +<central/**>

# --- 2. SCHEDA SENSORE ---
[env:h7_m7_sensor_real]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
    WiFi.h
    WiFiUdp.h
build_flags =
    -I../../shared_lib
lib_ldf_mode = deep+
build_src_filter = +<sensor/**>


