[platformio]
extra_configs = ../../common_config.ini

# --- 1. SCHEDA CENTRALE (GATEWAY) ---
[env:h7_m7_multi_central]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
    WiFi.h
    WiFiUdp.h
lib_ldf_mode = deep+
build_src_filter = +<central/**>

# --- 2. SCHEDA SENSORE 1 ---
[env:h7_m7_multi_sensor_1]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
    WiFi.h
    WiFiUdp.h
build_flags =
    -I../../shared_lib
    -DSENSOR_ID=01  # <--- Definisce l'ID 1
lib_ldf_mode = deep+
build_src_filter = +<sensor/**>

# --- 3. SCHEDA SENSORE 2 ---
[env:h7_m7_multi_sensor_2]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
    WiFi.h
    WiFiUdp.h
build_flags =
    -I../../shared_lib
    -DSENSOR_ID=02  # <--- Definisce l'ID 2
lib_ldf_mode = deep+
build_src_filter = +<sensor/**>