[platformio]
extra_configs = ../../common_config.ini

# --- Test base ---
[env:h7_test_MultiThreading]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
    chrono
build_src_filter = +<base/**>

# --- Test Mutex ---
[env:h7_test_MultiThreading_Mutex]
extends = m7_base
lib_deps = 
    ${common.lib_deps}
    chrono
build_src_filter = +<mutex/**>